### ISSUE TITLE
One issue on ToBigInteger()

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo-devpack-dotnet#202]
I try to build https://github.com/neo-project/neo-devpack-dotnet/pull/187 again due to the latest devpack-dotnet, it failed.
```
1>------ Rebuild All started: Project: Neo.SmartContract.Framework, Configuration: Debug Any CPU ------
1>Neo.SmartContract.Framework -> D:\Master-smoking\2020-03-13\neo-devpack-dotnet-lightzero\src\Neo.SmartContract.Framework\bin\Debug\netstandard2.1\Neo.SmartContract.Framework.dll
2>------ Rebuild All started: Project: Template.NEP5.CSharp, Configuration: Debug Any CPU ------
2>Template.NEP5.CSharp -> D:\Master-smoking\2020-03-13\neo-devpack-dotnet-lightzero\templates\Template.NEP5.CSharp\bin\Debug\netstandard2.1\Template.NEP5.CSharp.dll
2>Neo.Compiler.MSIL console app v3.0.0.0
2>EXEC : Convert error : System.Exception: error:System.Byte[] Template.NEP5.CSharp.NEP5::Owner()::IL_0002 Newarr
2> ---> System.Exception: _ConvertNewArr::not support var lens for new byte[?].
2>   at Neo.Compiler.MSIL.ModuleConverter._ConvertNewArr(ILMethod method, OpCode src, NeoMethod to) in D:\Master-smoking\2020-03-13\neo-devpack-dotnet\src\Neo.Compiler.MSIL\MSIL\Conv_Multi.cs:line 1151
2>   at Neo.Compiler.MSIL.ModuleConverter.ConvertCode(ILMethod method, OpCode src, NeoMethod to) in D:\Master-smoking\2020-03-13\neo-devpack-dotnet\src\Neo.Compiler.MSIL\MSIL\Converter.cs:line 853
2>   at Neo.Compiler.MSIL.ModuleConverter.FillMethod(ILMethod from, NeoMethod to, Boolean withReturn) in D:\Master-smoking\2020-03-13\neo-devpack-dotnet\src\Neo.Compiler.MSIL\MSIL\Converter.cs:line 408
2>   --- End of inner exception stack trace ---
2>   at Neo.Compiler.MSIL.ModuleConverter.FillMethod(ILMethod from, NeoMethod to, Boolean withReturn) in D:\Master-smoking\2020-03-13\neo-devpack-dotnet\src\Neo.Compiler.MSIL\MSIL\Converter.cs:line 412
2>   at Neo.Compiler.MSIL.ModuleConverter.Convert(ILModule _in, ConvOption option) in D:\Master-smoking\2020-03-13\neo-devpack-dotnet\src\Neo.Compiler.MSIL\MSIL\Converter.cs:line 92
2>   at Neo.Compiler.Program.Compile(Options options) in D:\Master-smoking\2020-03-13\neo-devpack-dotnet\src\Neo.Compiler.MSIL\Program.cs:line 159
2>D:\Master-smoking\2020-03-13\neo-devpack-dotnet-lightzero\templates\Template.NEP5.CSharp\Template.NEP5.CSharp.csproj(12,5): error MSB3073: The command "neon -f "D:\Master-smoking\2020-03-13\neo-devpack-dotnet-lightzero\templates\Template.NEP5.CSharp\bin\Debug\netstandard2.1\Template.NEP5.CSharp.dll" -o" exited with code -1.
2>Done building project "Template.NEP5.CSharp.csproj" -- FAILED.
========== Rebuild All: 1 succeeded, 1 failed, 0 skipped ==========
```
![image](https://user-images.githubusercontent.com/38493437/76515305-50196380-6494-11ea-8b0d-9256764adb6c.png)

The previous compiler return this, it works well:
![image](https://user-images.githubusercontent.com/38493437/76514723-4c391180-6493-11ea-9f24-3c7317937362.png)

@lightszero

**Comment by lightszero** [comment]
I will check,
Use this fornow.
  private readonly static byte[] Owner =  new byte[] { 0xf6, 0x64, 0x43, 0x49, 0x8d, 0x38, 0x78, 0xd3, 0x2b, 0x99, 0x4e, 0x4e, 0x12, 0x83, 0xc6, 0x93, 0x44, 0x21, 0xda, 0xfe };

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Owen Zhang<mailto:notifications@github.com>
发送时间: 2020年3月12日 19:05
收件人: neo-project/neo-devpack-dotnet<mailto:neo-devpack-dotnet@noreply.github.com>
抄送: lights li<mailto:lightsever@hotmail.com>; Mention<mailto:mention@noreply.github.com>
主题: [neo-project/neo-devpack-dotnet] One issue on ToBigInteger() (#202)


I try to build #187<https://github.com/neo-project/neo-devpack-dotnet/pull/187> again due to the latest devpack-dotnet, it failed.

1>------ Rebuild All started: Project: Neo.SmartContract.Framework, Configuration: Debug Any CPU ------

1>Neo.SmartContract.Framework -> D:\Master-smoking\2020-03-13\neo-devpack-dotnet-lightzero\src\Neo.SmartContract.Framework\bin\Debug\netstandard2.1\Neo.SmartContract.Framework.dll

2>------ Rebuild All started: Project: Template.NEP5.CSharp, Configuration: Debug Any CPU ------

2>Template.NEP5.CSharp -> D:\Master-smoking\2020-03-13\neo-devpack-dotnet-lightzero\templates\Template.NEP5.CSharp\bin\Debug\netstandard2.1\Template.NEP5.CSharp.dll

2>Neo.Compiler.MSIL console app v3.0.0.0

2>EXEC : Convert error : System.Exception: error:System.Byte[] Template.NEP5.CSharp.NEP5::Owner()::IL_0002 Newarr

2> ---> System.Exception: _ConvertNewArr::not support var lens for new byte[?].

2>   at Neo.Compiler.MSIL.ModuleConverter._ConvertNewArr(ILMethod method, OpCode src, NeoMethod to) in D:\Master-smoking\2020-03-13\neo-devpack-dotnet\src\Neo.Compiler.MSIL\MSIL\Conv_Multi.cs:line 1151

2>   at Neo.Compiler.MSIL.ModuleConverter.ConvertCode(ILMethod method, OpCode src, NeoMethod to) in D:\Master-smoking\2020-03-13\neo-devpack-dotnet\src\Neo.Compiler.MSIL\MSIL\Converter.cs:line 853

2>   at Neo.Compiler.MSIL.ModuleConverter.FillMethod(ILMethod from, NeoMethod to, Boolean withReturn) in D:\Master-smoking\2020-03-13\neo-devpack-dotnet\src\Neo.Compiler.MSIL\MSIL\Converter.cs:line 408

2>   --- End of inner exception stack trace ---

2>   at Neo.Compiler.MSIL.ModuleConverter.FillMethod(ILMethod from, NeoMethod to, Boolean withReturn) in D:\Master-smoking\2020-03-13\neo-devpack-dotnet\src\Neo.Compiler.MSIL\MSIL\Converter.cs:line 412

2>   at Neo.Compiler.MSIL.ModuleConverter.Convert(ILModule _in, ConvOption option) in D:\Master-smoking\2020-03-13\neo-devpack-dotnet\src\Neo.Compiler.MSIL\MSIL\Converter.cs:line 92

2>   at Neo.Compiler.Program.Compile(Options options) in D:\Master-smoking\2020-03-13\neo-devpack-dotnet\src\Neo.Compiler.MSIL\Program.cs:line 159

2>D:\Master-smoking\2020-03-13\neo-devpack-dotnet-lightzero\templates\Template.NEP5.CSharp\Template.NEP5.CSharp.csproj(12,5): error MSB3073: The command "neon -f "D:\Master-smoking\2020-03-13\neo-devpack-dotnet-lightzero\templates\Template.NEP5.CSharp\bin\Debug\netstandard2.1\Template.NEP5.CSharp.dll" -o" exited with code -1.

2>Done building project "Template.NEP5.CSharp.csproj" -- FAILED.

========== Rebuild All: 1 succeeded, 1 failed, 0 skipped ==========

[image]<https://user-images.githubusercontent.com/38493437/76515305-50196380-6494-11ea-8b0d-9256764adb6c.png>

The previous compiler return this, it works well:
[image]<https://user-images.githubusercontent.com/38493437/76514723-4c391180-6493-11ea-9f24-3c7317937362.png>

@lightszero<https://github.com/lightszero>

―

**Comment by lightszero** [comment]
@superboyiii can we close this?

**Comment by superboyiii** [comment]
> @superboyiii can we close this?

Sure.
