### ISSUE TITLE
Configure manifest.groups & manifest.permission without manually editing manifest file

### ISSUE THREAD

**Issue by wanglongfei88** [neo-project/neo-devpack-dotnet#205]
In contract manifest file, there is some attributes, like manifest.groups, manifest.permissions, or metadatta. I think these attributes are pretty important for smart contract that is why they are included in manifest file. 

But as I know at this point, if we need to config those attributes, developers need to manually edit manifest.json file which is not very friendly. 

Therefore, can we consider to provide the function to config those attributed without manually editing manifest file ?

**Comment by shargon** [comment]
Do you think that it will be different or easier for the user between configure a json or calling a method?

**Comment by Tommo-L** [comment]
I checked that we had too many configuration properties to fit into the contract. Otherwise our contract will become a configuration file. 

Here is an example, we have `groups`, `features`, `permissions`, `trusts` and `safeMethods`.
```json
{
	"groups": [],
	"features": {
		"storage": true,
		"payable": true
	},
	"abi": {
		"hash": "0x13f98375a2a5bf2c8ab9a71b7c1a66d0a96f82bf",
		"methods": [{
			"name": "main",
			"parameters": [{
				"name": "account",
				"type": "ByteArray"
			}],
			"returnType": "Integer",
                       "offset": "0x00"
		}]
	},
	"permissions": [{
		"contract": "*",
		"methods": "*"
	}],
	"trusts": [],
	"safeMethods": []
}
```
I think we should set a more open default configuration parameter. In most case, developers don't have to care about the manifest file. Only when they want to have a high level security, they just modfiy the manifest file.
